export const ADD_FEEDBACK = "ADD_FEEDBACK";
export const RETRIEVE_FEEDBACKS = "RETRIEVE_FEEDBACKS";
export const UPDATE_FEEDBACK = "UPDATE_FEEDBACK";
//export const DELETE_FEEDBACK = "DELETE_FEEDBACK";
